[[main]]
name = "docs"
pageRef = "docs"
weight = 1

[[main]]
name = "vgc-zero"
pageRef = "docs/vgc-zero"
parent = "docs"

[[main]]
name = "blog"
pageRef = "posts"
weight = 2

[[main]]
identifier = "github"
pre = "github"
url = "https://github.com/chili-chip"
weight = 3

[[main]]
identifier = "discord"
pre = "discord"
url = "https://discord.gg/xB9sPYKBZc"
weight = 4

[[footer]]
none = "none"

[[footer]]
name = "tags"
pageRef = "tags"
weight = 1