colorScheme = "fire"
defaultAppearance = "dark"
autoSwitchAppearance = true
enableSearch = true
enableCodeCopy = true
defaultBackgroundImage = "background.png"
firebase = { }
fathomAnalytics = { }
verification = { }

[header]
layout = "fixed"

[footer]
showCopyright = true
showThemeAttribution = false
showAppearanceSwitcher = true
showScrollToTop = true

[homepage]
layout = "background"
homepageImage = "background.png"
showRecent = true
showRecentItems = 3
showMoreLink = true
showMoreLinkDest = "/posts"
cardView = true
cardViewScreenWidth = false
layoutBackgroundBlur = false

[article]
showDate = true
showDateUpdated = false
showAuthor = true
showHero = true
heroStyle = "thumbAndBackground"
layoutBackgroundHeaderSpace = false
showRelatedContent = true
relatedContentLimit = 3
showBreadcrumbs = true
showDraftLabel = true
showEdit = false
editAppendPath = true
seriesOpened = false
showHeadingAnchors = true
showPagination = true
invertPagination = false
showReadingTime = true
showTableOfContents = true
showTaxonomies = false
showAuthorsBadges = false
showWordCount = true
showSummary = true
showZenMode = true
sharingLinks = [
  "linkedin",
  "twitter",
  "whatsapp",
  "pinterest",
  "reddit",
  "facebook",
  "email"
]

[list]
showBreadcrumbs = true
showSummary = true
showTableOfContents = false
showCards = false
groupByYear = true
cardView = true
cardViewScreenWidth = false
showHero = true
heroStyle = "background"
layoutBackgroundHeaderSpace = false

[sitemap]
excludedKinds = [ ]

[taxonomy]
showTermCount = true
